### ISSUE TITLE
Flash of unstyled content on load

### ISSUE THREAD

**Issue by coryhouse** [webpack/style-loader#107]
Since this loader stores styles in JavaScript and then uses JavaScript to inject the styles onto the page, there is a flash of unstyled content on page load. The styles aren't actually applied until the JavaScript is parsed and the styles are injected into the head. 

This issue strikes me as inherent in the design, but is there a workaround for this?

To see this issue, use Chrome.

**Comment by tizmagik** [comment]
You can use the `ExtractTextPlugin()` to extract your CSS into a .css stylesheet which you can reference in the page as you normally would any external stylesheet. Most of the React/Webpack startkits have this for production mode and use the JS-loaded styles in development mode for live/hot loading.

**Comment by coryhouse** [comment]
Cool, that's exactly what I just did. :) Just making sure there wasn't another way to pull this off. Thanks for the quick reply!

**Comment by rr-riag** [comment]
i was curious to see if i could get it to work without using the ExtractTextPlugin..

first in the html or within some css that's not imported into a JS file add something like the following..
```
...
    <style>
        body.loading {
            visibility: hidden;
        }
    </style>
</head>
<body class="loading">
...
```

then inside the JS file that renders the app.. (it's a bit hacky but it works)

```
ReactDOM.render(
    <App/>,
    document.getElementById('app'),
    () => {
        window.setTimeout(() => {
            window.setTimeout(() => {
                document.body.classList.remove('loading');
            });
        });
    }
);
```
i don't know why it needs to wait 2 cycles of the event loop, 0 or 1 isn't enough here but that seems to do it

**Comment by manvalls** [comment]
That flash is caused by the delay of loading the blob created on the fly to support source maps. Either disable sourcemaps for your css or add the `singleton` option to fix it.
