### ISSUE TITLE
Angular2 - ERROR: Expected 'styles' to be an array of strings.

### ISSUE THREAD

**Issue by IAMtheIAM** [webpack/style-loader#123]
Why does using style-loader with angular2 components and required css produce this error?

Webpack
```        loaders: ['style', 'css?sourceMap', 'sass?sourceMap']```

Angular 2 component
```  styles: [
    require('normalize.css'),
    require('./app.scss')
  ],```

> Error: Expected 'styles' to be an array of strings.
>     at new BaseException (exceptions.js:17)
>     at Object.assertArrayOfStrings (assertions.js:13)
>     at CompileMetadataResolver.getDirectiveMetadata (metadata_resolver.js:64)
>     at RuntimeCompiler.resolveComponent (runtime_compiler.js:34)
>     at application_ref.js:99
>     at application_ref.js:292
>     at ZoneDelegate.invoke (zone.js:323)
>     at Object.NgZoneImpl.inner.inner.fork.onInvoke (ng_zone_impl.js:45)
>     at ZoneDelegate.invoke (zone.js:322)
>     at Zone.run (zone.js:216)
>     at NgZoneImpl.runInner (ng_zone_impl.js:76)
>     at NgZone.run (ng_zone.js:223)
>     at ApplicationRef_.run (application_ref.js:290)
>     at Object.coreLoadAndBootstrap (application_ref.js:96)
>     at Object.bootstrap (platform_browser_dynamic.js:91)
>     at main (main.browser.ts:24)
>     at HTMLDocument.<anonymous> (webpack-hmr.ts:57)
>     at ZoneDelegate.invokeTask (zone.js:356)
>     at Zone.runTask (zone.js:256)
>     at HTMLDocument.ZoneTask.invoke (zone.js:423)
> 

If I use styleUrls instead: ```  styleUrls: [
    require('normalize.css'),
    require('./app.scss')
  ],```

I get a different error:

> main.browser.ts:31 Failed to load %5Bobject%20Object%5D


What am I doing wrong?

**Comment by borntorun** [comment]
Did you resolved this issue?

**Comment by daddywoodland** [comment]
I ripped off a solution from the [angular class web pack starter](https://github.com/AngularClass/angular2-webpack-starter).  They use the 'to-string-loader' for css.

`  {
        test: /\.css$/,
        loaders: ['to-string-loader', 'css-loader']
      }`

Haven't tried a production version yet but it got me going in dev.

**Comment by borntorun** [comment]
I'm using 'extract-text-webpack-plugin' to extract css styles in a separate css file and I could not figure yet why I get these errors. 

```
{
        test: /\.css$/,
        loader: ExtractTextPlugin.extract('style', 'css?sourceMap')
}
```

Thanks anyway for the feedback.

**Comment by dingfengsaniao** [comment]
@borntorun  I got the same problem just like you....did you resolve this issue?

**Comment by daddywoodland** [comment]
@dingfengsaniao @borntorun This is a bit of a guess but I don't think the ExtractTextPlugin is 'overiding' Angular2's behaviour on the styles property, so whilst it's bundling everything up, Angular isn't really aware of the changes.

We got it working by importing global styles at the bootstrap level, rather than requiring them in the component style property.  That way ExtractTextPlugin knows to pull them into a bundle.

Then we're explicitly bundling the component specific styles as raw text in the js module, so they're scoped to the component and get past the 'array of string' problem.

`//webpack.config { 
	// Load sass files from the theme folder only then convert to css and bundle them 
	test: /\.scss$/, 
	include: helpers.root('src/theme'), 
	loader: extractTextPlugin.extract('style', 'css?postcss!sass') 
}, 
{ 
	// Load sass files from within the application folder then convert to a string, then css and include in the javascript module 
	test: /\.scss$/, 
	include: helpers.root('src/app'), 
	loader: 'raw!postcss!sass' 
} `

**Comment by dingfengsaniao** [comment]
@daddywoodland  this actually works!!! thank you very much!!!!

**Comment by jrgleason** [comment]
What about this (it is what I did)....

    String(require('./app.component.styl'))

**Comment by Alex51482** [comment]
Has anyone solved this yet?

**Comment by Alex51482** [comment]
This is my workaround: ``

 styles:[require('./app.component.css').**toString**()]``

**Comment by Alex51482** [comment]
Sorry am a total noob on this and am sorry.  But I wanted to share my last workaround that finally worked for me.

I started with WebPack Sample here: [](https://angular.io/docs/ts/latest/guide/webpack.html )

Added to-string-loader dependency here -> [](https://github.com/gajus/to-string-loader) 

In my wepback.common.js file I added the loader:

```
 {
        test: /\.css$/,
        exclude: helpers.root('src', 'app'),
        loaders:[ExtractTextPlugin.extract('style', 'css-loader'), **'to-string', 'css'**]
      },
```
I am new to all of this so I apologize ahead of time if I suggested something dumb...but it works for me. =)

**Comment by aarmora** [comment]
@jrgleason Killed it.  Nice work, man!

**Comment by iacii** [comment]
@Alex-Torres Thanks for sharing your solution! This worked for me and preserved view encapsulation which I couldn't get to work with some of the other suggestions.

**Comment by Nexxado** [comment]
@Alex-Torres Thank you, works for me as well.
and no need for "require" inside my component.

**Comment by wittibs** [comment]
@IAMtheIAM to answer your original question:
1. sass loader compiles your SASS down to CSS,
2. css loader resolves css imports and url(..)
3. style loader **injects result into DOM within a style tag**
The style loader is not returning a string as a result. You get the error because Angular 2 Component styles property expects an array of strings.
This should work ...
`loaders: ['raw', 'sass']`
raw loader returns a string representing your CSS (compiled from SASS), which is what we want.
Angular 2 will then take care of injecting your styles into the DOM.
See more info [here](https://github.com/AngularClass/angular2-webpack-starter/issues/136).

**Comment by pchiwan** [comment]
@wittibs YES! that did it, thanks man!

**Comment by SpaceK33z** [comment]
@wittibs answer is correct, so closing.

**Comment by xtianus79** [comment]
This is still an issue

**Comment by xtianus79** [comment]
@SpaceK33z @Alex-Torres @wittibs I thought your solutions where the answer but alas they were not.  It produces a file but it doesn't actual process the sass scss in a normal format.  if I put in a variable for example it just shoe horns in the variable as if it were all string text.  nothing actually gets processed.  It's fine if it is plain css but if you're trying to actually use sass... no go.

**Comment by wittibs** [comment]
@xtianus79 it sounds like you don't have sass-loader _or_ your webpack config isn't properly targeting sass files.

**Comment by tianyatomy** [comment]
@Alex-Torres Thank you so much!!!
This line works perfect for my application :
loaders:[ExtractTextPlugin.extract('style', 'css-loader'), 'to-string', 'css']

**Comment by Jeky11** [comment]
@Alex-Torres Thank you! This is latest version
"@angular/***": "2.2.3"
"angular2-template-loader": "0.6.0",
"extract-text-webpack-plugin": "2.0.0-beta.4",
"webpack": "2.1.0-beta.27",
"css-loader": "0.26.0",
"to-string-loader": "1.1.5"

> {
    test: /\.css$/,
    //loader: "to-string-loader!style-loader!css-loader?sourceMap"
    loaders: [
					ExtractTextPlugin.extract( { fallbackLoader: "style-loader", loader: 'css-loader' } ),
					'to-string-loader',
					'css-loader?sourceMap'
				]
			},

**Comment by FreezeSoul** [comment]
Thk
@wittibs

**Comment by tux2323** [comment]
For me this webpack setup works:
```javascript  
...
    let extractCSS = new ExtractTextPlugin('app.css');
...
     // loader config for global css files
     {
          test: /\.scss$/,
          exclude: [/node_modules/, /src\/app/],
          loader: extractCSS.extract('style-loader', 'raw!css!sass'),
      },
     // loader config for angular component styles 
      {   
          test: /\.scss$/, 
          exclude: [/node_modules/, /src\/styles/], 
          loader: 'raw!css!sass'
      },
...
      plugins: [
        new HtmlWebpackPlugin({
          template: 'src/app/index.html',
          hash: true,
        }),
        extractCSS
      ],
```

**Comment by JefferyHus** [comment]
for anyone who still has this issue, this is what I have used for a less stylesheet files:
```json
        module:{
            loaders:[
                .....
                {test: /\.less$/, loaders: [ExtractTextPlugin.extract("style-loader", "css-loader!less-loader")]}
               .....
            ]
        },
```

**Comment by DerZyklop** [comment]
It‘s still an issue if you want sourceMaps AND scss (like @IAMtheIAM in the initial comment). 

1: [This](https://github.com/webpack-contrib/style-loader/issues/123#issuecomment-227109937) works for **css**.

2: [This](https://github.com/webpack-contrib/style-loader/issues/123#issuecomment-227185413) works for **css + souceMap**.

3: [This](https://github.com/webpack-contrib/style-loader/issues/123#issuecomment-240862326) works for **scss**.

But what‘s with **scss  + souceMap**?

When i try **1** with scss, then i don‘t get my sourceMap:

    {
        test: /\.scss$/,
        loaders: ['to-string-loader', 'css-loader?sourceMap', 'sass-loader?sourceMap']
    }

When i do **2** with scss, then i am back at the initial issue `Expected 'styles' to be an array of strings`

    {
            test: /\.css$/,
            loader: ExtractTextPlugin.extract('style', 'css?sourceMap')
    }

When i do **3** with sourceMap, i don’t get a sourceMap.

    {
        test: /\.scss$/,
        loaders: ['raw', 'sass?sourceMap']
    }

And finally i translated @JefferyHus 's solution to scss.

    {
        test: /\.scss$/,
        loaders: [
            ExtractTextPlugin.extract("style-loader", "css-loader!sass-loader")
        ]
    }

but then the command line gives me

    ERROR in ./src/components/app/app.component.scss
    Module parse failed: /my/project/path/node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"extract":true,"remove":true}!style-loader!css-loader!sass-loader!/my/project/path/src/components/app/app.component.scss Unexpected token (1:0)
    You may need an appropriate loader to handle this file type.

**Comment by JefferyHus** [comment]
@DerZyklop Have you tried this sass loader?
https://github.com/jtangelder/sass-loader
as described in the RADME.md to load sass files using css loader to extract styles you will have to do so:
If you need to define two different loader configs, you can also change the config's property name via sass-loader?config=otherSassLoaderConfig:
```javascript
module.exports = {
  ...
  module: {
    loaders: [
      {
        test: /\.scss$/,
        loaders: ["style-loader", "css-loader", "sass-loader?config=otherSassLoaderConfig"]
      }
    ]
  },
  otherSassLoaderConfig: {
    ...
  }
};
```
try this solution and if it works let us know thanks.

**Comment by j-nord** [comment]
Since webpack 2 runs nothing. The message comes with all solutions. Finding the error in large projects is futile, because Webpack 2 simply does not issue a proper error message.

How can you really find the error. The existing solutions do not help any further. We have now found over 20 such alleged solutions. We look for 2 days the error but always the same error message:

**"Expected 'styles' to be an array of strings vendor webpack 2"**

Is there a real solution ?

**Comment by kutuev** [comment]
@j-nord that's my solution:

{
                test: /\.css$/,
                exclude: path.join(__dirname,'/public/app'),
                loader: extractCss.extract({fallback: 'style-loader', use: 'css-loader'})
            },
            {
                test: /\.css$/,
                include: path.join(__dirname,'/public/app'),
                use: [
                {
                    loader: 'to-string-loader'
                },
                {
                    loader: 'css-loader'
                }]
            },

So, the main idea is include/exclude a public folder 

Thanks,
Alexander

**Comment by deot** [comment]
you can try it,I solved the problem, but I was still very surprised
```js
// loader config for angular component styles 
{
  test: /\.(scss|css)$/,
  use: ['raw-loader','sass-loader'], // don't use css-loader for ng2 （unusual）
},
// loader config for global css files
{
  test: /\.scss$/,
  exclude: [/node_modules/, /src\/app/], 
  use: ExtractTextPlugin.extract({
    fallbackLoader: 'style-loader',
    use: ['css-loader','sass-loader']
  })
},
```

**Comment by DhanushKS** [comment]
css not rendering globally angular-2
can anyone help

zone_symbol__error
:
Error: Expected 'styles' to be an array of strings. at assertArrayOfStrings

@Component({
....
styleUrls: ['./../styles.css'],
})

**Comment by alex88** [comment]
@deot but in your case, does image referencing works?

**Comment by josueadelima** [comment]
This configuration works for me

```
      {
        test: /\.(png|jpe?g|gif|svg|woff|woff2|ttf|eot|ico)$/,
        loader: 'file-loader?name=assets/[name]-[hash].[ext]'
      },
      {
        test: /\.css$/,
        exclude: helpers.root('src', 'app'),
        loader: ExtractTextPlugin.extract({ fallbackLoader: 'style-loader', loader: 'css-loader?sourceMap' })
      },
      {
        test: /\.sass$/,
        include: helpers.root('src', 'app'),
        loader: ['css-to-string-loader','css-loader','sass-loader'] 
      },
      {
        test: /\.css$/,
        include: helpers.root('src', 'app'),
        loader: ['css-to-string-loader','css-loader']
      }
```

**Comment by nickproz** [comment]
Thank you very much sir. It complained that 'loader' should be 'loaders', but otherwise, worked for me! <3

**Comment by josueadelima** [comment]
@nickproz its weird I have it in singular and works without any problem, I'll try in plural, actually makes more sense plural than singular, I'm using this configuration because, if for example you use raw, then css is not parsed and url for background-images, doesn't get hashed if your are using hashes for cache, css-to-string-loader makes the trick :-)

**Comment by xtianus79** [comment]
I started this issue because while it is related I don't believe it is the same thing

https://github.com/angular/angular-cli/issues/6002

**Comment by Loppone** [comment]
It's two days i try everything but when i fix the app in production it crashes in development and viceversa. This is my working configuration in production:

```
var webpack = require('webpack');

const ExtractTextPlugin = require("extract-text-webpack-plugin");
const extractSass = new ExtractTextPlugin({
    filename: "bundle.css",
    disable: process.env.NODE_ENV === "development"
});

module.exports = {
    entry: {
        'app': './assets/app/main.ts'
    },

    resolve: {
        extensions: ['.js', '.ts']
    },

    module: {
        rules: [
            {
                test: /\.html$/,
                use: [{ loader: 'html-loader' }]
            },
            {
                test: /\.css$/,
                use: [{ loader: 'raw-loader' }]
            },
            {
                test: /\.scss$/,
                use: extractSass.extract({
                    use: [{
                        loader: "css-loader"
                    }, {
                        loader: "sass-loader"
                    }],
                    fallback: "style-loader"
                })
            }],
        exprContextCritical: false
    },
    plugins: [
        extractSass
    ]
};

```

My component:

```
@Component({
  styleUrls: ['./auth.component.scss','../common/common.scss']
})

```

I tried thousand of combinations, but none was working.
Thanks in advance

**Comment by ManuLintz** [comment]
I needed to require a CSS file from a nodemodule in an Angular 4 component and this worked for me: 
`  styles: [ require('css-to-string-loader!style-loader!module/dist/file.css')]`

**Comment by fabio-coolshop** [comment]
my fix
<pre>
module: {
     rules: [{
          test: /\.scss$/,
          use: [{
               loader: "raw-loader"
          },{
               loader: "style-loader"
          },{
               loader: "css-loader"
          },{
               loader: "sass-loader"
          }]
     }]
}
</pre>

**Comment by vivek-vidhema** [comment]
Thanks @daddywoodland 
`{ test: /\.css$/, loaders: ['to-string-loader', 'css-loader'] }`
this worked like a charm

**Comment by ShoaibIqbal452** [comment]
I am using sass in my project and following is my webpack_base_config.js
`const webpack = require("webpack")
const path = require("path")
const config = require("./config")
const ExtractTextPlugin = require("extract-text-webpack-plugin")

module.exports = {
    "cache": true,
    "entry": {
        "polyfills": path.join(__dirname, "..", "src", "polyfills.ts"),
        "vendor": path.join(__dirname, "..", "src", "vendor.ts"),
        "client": path.join(__dirname, "..", "src", "main.ts"),
        "styles": path.join(__dirname, "..", "src", "styles.scss")
    },
    "output": {
        "filename": "[name].js",
        "path": config.build.assetsRoot,
        "publicPath": process.env.NODE_ENV === "production"
            ? config.build.assetsPublicPath
            : config.dev.assetsPublicPath
    },
    "resolve": {
        "extensions": [".ts", ".js"]
    },
    "module": {
        "rules": [
            {
                "test": /\.ts$/,
                "loaders": [
                    {
                        "loader": "awesome-typescript-loader",
                        "options": {
                            // specify your tsconfig.json file
                            "configFileName": path.join(__dirname, "..", "tsconfig.json")
                        }
                    },
                    "angular2-template-loader"
                ]
            },
            {

                "test": /\.scss|\.css$/,
                "loader": ExtractTextPlugin.extract({
                    "fallback": "style-loader",
                    "use": ["css-loader",
                        {
                            "loader": "sass-loader"
                        }]
                })
            },
            {
                "test": /\.html$/,
                "loaders": ["html-loader"]
            },
            {
                "test": /\.(ttf|eot|svg|woff|woff2)$/,
                "loader": "file-loader?name=fonts/[name].[ext]"
            }
        ]
    },

    "plugins": [
        // bundle all you styling into one style.css file
        new ExtractTextPlugin({ "filename": "styles.css", "allChunks": true }),

        // create chunks for entries
        new webpack.optimize.CommonsChunkPlugin({
            "name": ["client", "vendor", "polyfills", "styles"]
        }),
    ]
}` 


When I run for dev it builds successfully but in browser it gives following error! 


vendor.js:40236 Uncaught Error: Expected 'styles' to be an array of strings.
    at assertArrayOfStrings (vendor.js:40236)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (vendor.js:51486)
    at CompileMetadataResolver._getEntryComponentMetadata (vendor.js:52203)
    at vendor.js:52189
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getEntryComponentsFromProvider (vendor.js:52188)
    at vendor.js:52152
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (vendor.js:52115)
    at vendor.js:52117
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver._getProvidersMetadata (vendor.js:52115)
    at vendor.js:51690
    at Array.forEach (<anonymous>)
    at CompileMetadataResolver.getNgModuleMetadata (vendor.js:51681)
    at JitCompiler._loadModules (vendor.js:63111)
    at JitCompiler._compileModuleAndComponents (vendor.js:63084)
    at JitCompiler.compileModuleAsync (vendor.js:63013)
    at PlatformRef_._bootstrapModuleWithZone (vendor.js:4745)
    at PlatformRef_.bootstrapModule (vendor.js:4731)
    at Object.c (client.js:sourcemap:38814)
    at __webpack_require__ (styles.js:712)
    at fn (styles.js:117)
    at Object.defineProperty.value (client.js:sourcemap:38795)
    at __webpack_require__ (styles.js:712)
    at webpackJsonpCallback (styles.js:26)
    at client.js:sourcemap:1
assertArrayOfStrings @ vendor.js:40236
CompileMetadataResolver.getNonNormalizedDirectiveMetadata @ vendor.js:51486
CompileMetadataResolver._getEntryComponentMetadata @ vendor.js:52203
(anonymous) @ vendor.js:52189
CompileMetadataResolver._getEntryComponentsFromProvider @ vendor.js:52188
(anonymous) @ vendor.js:52152
CompileMetadataResolver._getProvidersMetadata @ vendor.js:52115
(anonymous) @ vendor.js:52117
CompileMetadataResolver._getProvidersMetadata @ vendor.js:52115
(anonymous) @ vendor.js:51690
CompileMetadataResolver.getNgModuleMetadata @ vendor.js:51681
JitCompiler._loadModules @ vendor.js:63111
JitCompiler._compileModuleAndComponents @ vendor.js:63084
JitCompiler.compileModuleAsync @ vendor.js:63013
PlatformRef_._bootstrapModuleWithZone @ vendor.js:4745
PlatformRef_.bootstrapModule @ vendor.js:4731
c @ client.js:sourcemap:38814
__webpack_require__ @ styles.js:712
fn @ styles.js:117
Object.defineProperty.value @ client.js:sourcemap:38795
__webpack_require__ @ styles.js:712
webpackJsonpCallback @ styles.js:26
(anonymous) @ client.js:sourcemap:1


I have tried almost 20 workaround's but nothing is working! can someone please help!

**Comment by k3lh4m** [comment]
For anyone that struggled with a similar problem, check this out.

Hope it helps other people out

https://stackoverflow.com/questions/41516346/error-expected-styles-to-be-an-array-of-strings/#43867625

**Comment by efronic** [comment]
@k3lh4m Thanks for the post. I have done it but I am getting this error with matchMedia: 

```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[0]
      An unhandled exception has occurred while executing the request
Microsoft.AspNetCore.NodeServices.HostingModels.NodeInvocationException: matchMedia is not defined
ReferenceError: matchMedia is not defined
    at new SidenavComponent (C:\Users\user\Documents\Visual Studio 2017\Projects\myapp.Forms\myapp.forms.api\ClientApp\dist\main-server.js:42199:9)
    at createClass (C:\Users\user\Documents\Visual Studio 2017\Projects\myapp.Forms\myapp.forms.api\ClientApp\dist\vendor.js:12858:20)
    at createDirectiveInstance (C:\Users\user\Documents\Visual Studio 2017\Projects\myapp.Forms\myapp.forms.api\ClientApp\dist\vendor.js:12703:37)
    at createViewNodes (C:\Users\user\Documents\Visual Studio 2017\Projects\myapp.Forms\myapp.forms.api\ClientApp\dist\vendor.js:14161:53)
    at callViewAction (C:\Users\user\Documents\Visual Studio 2017\Projects\myapp.Forms\myapp.forms.api\ClientApp\dist\vendor.js:14595:13)
    at execComponentViewsAction (C:\Users\user\Documents\Visual Studio 2017\Projects\myapp.Forms\myapp.forms.api\ClientApp\dist\vendor.js:14504:13)
    at createViewNodes (C:\Users\user\Documents\Visual Studio 2017\Projects\myapp.Forms\myapp.forms.api\ClientApp\dist\vendor.js:14189:5)
    at createRootView (C:\Users\user\Documents\Visual Studio 2017\Projects\myapp.Forms\myapp.forms.api\ClientApp\dist\vendor.js:14050:5)
    at Object.createProdRootView [as createRootView] (C:\Users\user\Documents\Visual Studio 2017\Projects\myapp.Forms\myapp.forms.api\ClientApp\dist\vendor.js:14743:12)
    at ComponentFactory_.module.exports.ComponentFactory_.create (C:\Users\user\Documents\Visual Studio 2017\Projects\myapp.Forms\myapp.forms.api\ClientApp\dist\vendor.js:11655:46)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance.<InvokeExportAsync>d__7`1.MoveNext()
```
Here is my component:
```
import { Component, OnInit, NgZone } from '@angular/core';

const SMALL_WIDTH_BREAKPOINT = 720;

@Component({
  selector: 'app-sidenav',
  templateUrl: './sidenav.component.html',
  styleUrls: ['./sidenav.component.scss']
})
export class SidenavComponent implements OnInit {

  private mediaMatcher: MediaQueryList =
    matchMedia(`(max-width: ${SMALL_WIDTH_BREAKPOINT}px)`);

  constructor(zone: NgZone) {
    this.mediaMatcher.addListener(mql => 
      zone.run(() => this.mediaMatcher = mql));
  }

  ngOnInit() {
  }

  isScreenSmall(): boolean {
    return this.mediaMatcher.matches;
  }

}
```
How can it be fixed?

**Comment by JohnnyKrds** [comment]
You have a style file without full extension.

It should be something like: "./app.component.scss"
But it's "./app.component."  -> notice that the "scss" is missing.

Rename your file to proper extension and update the .ts file that references it.

Best regards.
