### ISSUE TITLE
Error loading loader-utils

### ISSUE THREAD

**Issue by Moezalez** [webpack/style-loader#140]
I get an error when using webpack@2.1.0-beta.20 and style-loader@0.13.1:

```bash
ERROR in ./src/components/login/Login.pcss
Module build failed: (SystemJS) ENOENT: no such file or directory, open '/Users/Name/project/loader-utils'
        Error: ENOENT: no such file or directory, open '/Users/Name/project/loader-utils'
            at Error (native)
        Error loading /Users/Name/project/loader-utils as "loader-utils" from /Users/Name/project/node_modules/style-loader/index.js
```

When trying to parse a css file.

Loader-utils is installed, but for some reason it looks in my project folder for it.

**Comment by plashenkov** [comment]
@Moezalez I have the same issue. Have you found a solution?

**Comment by Moezalez** [comment]
@plashenkov nope, I just rolled back to webpack 1

**Comment by mikestead** [comment]
Not sure if the same cause as raised but for me this was an incompatibility of the latest `postcss-import` with webpack 2. As recommended [here](https://github.com/webpack/webpack/issues/2901) locking `postcss-import` to version `8.1.0` fixed the issue for me.

**Comment by hyperh** [comment]
Getting the same issue.

**Comment by danielmhanover** [comment]
+1

**Comment by evilebottnawi** [comment]
@danielmhanover please update your `postcss-import` to latest version (also check version `webpack` and `style-loader`).
