### ISSUE TITLE
Please add example config for webpack 2

### ISSUE THREAD

**Issue by kristianmandrup** [webpack/style-loader#156]
I would assume for webpack 2, it is

```js
  module: {
    rules: [
      { 
         test: /\.css$/, 
         loader: "style-loader!css-loader" 
      },
   ]
}
```

Please correct me if I'm wrong

**Comment by SpaceK33z** [comment]
This will be updated soon, see https://github.com/webpack/webpack/issues/3195 for more info.

**Comment by kristianmandrup** [comment]
Ah, thanks! I still see most of the webpack 2 examples using the `loaders` key... but it seems to works for now. 

Apparently for beta 25 or less it still works without the `-loader`, but with beta 28 it errors and tells me to use specify the full name ie `css-loader` etc.
Cheers!
