### ISSUE TITLE
Loader expose filesystem paths

### ISSUE THREAD

**Issue by unlight** [webpack/style-loader#28]
I use:
`require("./design/style.css");`
Part of config:
```js
        loaders: [
          { test: /\.css$/, loader: 'style!css' }
        ]
```
Result somewhere in `build/bundle.js`:
```js
	// style-loader: Adds some css to the DOM by adding a <style> tag

	// load the styles
	var content = __webpack_require__(7);
	if(typeof content === 'string') content = [[module.id, content, '']];
	// add the styles to the DOM
	var update = __webpack_require__(14)(content);
	// Hot Module Replacement
	if(false) {
		// When the styles change, update the <style> tags
		module.hot.accept("!!D:\\My\\Dev\\Project\\node_modules\\css-loader\\index.js!D:\\My\\Dev\\Project\\src\\design\\style.css", function() {
			var newContent = require("!!D:\\My\\Dev\\Project\\node_modules\\css-loader\\index.js!D:\\My\\Dev\\Project\\src\\design\\style.css");
			if(typeof newContent === 'string') newContent = [module.id, newContent, ''];
			update(newContent);
		});
		// When the module is disposed, remove the <style> tags
		module.hot.dispose(function() { update(); });
	}
```
Need to get rid of absolute paths!

**Comment by doliver3** [comment]
+1 for the ability to remove these paths for the non-minimized version

**Comment by cliren** [comment]
+2 to remove absolute paths when non minimized. I am not sure how the below block is executed when its falsy but the local-paths will cause a problem when multiple module bundlers are used. For example a module built with webpack is included in a module built with browerify doesn't eliminate the local paths.

	// Hot Module Replacement
	if(false) {
		// When the styles change, update the <style> tags
		module.hot.accept("!!/Users/local-path", function() {
			var newContent = require("!!/Users/localpath");
			if(typeof newContent === 'string') newContent = [module.id, newContent, ''];
			update(newContent);
		});
		// When the module is disposed, remove the <style> tags
		module.hot.dispose(function() { update(); });
	}

**Comment by sompylasar** [comment]
@jehoshua02 You are right [in your comment](https://github.com/webpack/style-loader/issues/28#issuecomment-63405193), the absolute filesystem path leaks [from here](https://github.com/webpack/core/blob/b69a87adf82935a3e4871b378d786d35b42496fb/lib/NormalModuleMixin.js#L225).

@sokra Could you give some insights on this issue? We likely should add a linked issue in the [webpack/core](https://github.com/webpack/core) repo. Such server-side data should not leak to the browser-side.

**Comment by jehoshua02** [comment]
I'd be happy if the paths were relative to the project root. That way when any team member builds it doesn't cause a diff.

**Comment by sokra** [comment]
@sompylasar It's on the TODO list. Not related to webpack/core.

**Comment by sompylasar** [comment]
@sokra Thank you for your attention. Maybe not related, I haven't tracked
it farther than webpack/core (where loaderContext comes from).

Is there a GitHub issue for this TODO list item to link to?

2015-01-12 15:36 GMT+03:00 Tobias Koppers <notifications@github.com>:

**Comment by sokra** [comment]
> Is there a GitHub issue for this TODO list item to link to?

Sorry you can't link to my brain ;)

**Comment by cliren** [comment]
@sokra the hot module code causes dependent build builds break on the path (browserify builds). Is this going to fixed soon?

**Comment by sokra** [comment]
fixed
