### ISSUE TITLE
0.8.2 breaks my tests running in the PhantomJS

### ISSUE THREAD

**Issue by rbtbar** [webpack/style-loader#31]
Hi, just a little bug i found:

I'm using the style-loader (since 0.8.1) in the following manner (just this one line):
require('!style!css!sass!./someFile.scss');

The version 0.8.2 seems to work under IE11, latest FF and latest Chrome, but it breaks execution of several tests in the PhantomJS. For the moment I'm keeping "0.8.1" in my list of depenencies....

Cheers,
rb

**Comment by nmccready** [comment]
Looks like you could use [this](https://www.npmjs.com/package/phantomjs-polyfill) as an alternative and load it into your karma.conf.

**Comment by sorrycc** [comment]
@nmccready Thanks. I just include this polyfill in my test runner page, and it resolved my problem.

**Comment by Ridermansb** [comment]
Works for me! Thanks @nmccready

**Comment by That-David-Guy** [comment]
Thanks @nmccready, worked like a charm

**Comment by SpaceK33z** [comment]
Closing for reasons stated in the PR #33.
