### ISSUE TITLE
Do something after styles have been updated

### ISSUE THREAD

**Issue by gaearon** [webpack/style-loader#37]
I want to apply viewport units polyfill on iOS 7 as soon as styles are added dynamically.

It's important I want to do this at runtime because it's optional — and I use `ExtractTextPlugin` so can't post-process all CSS on client side.

What would be the easiest way to do something after styles have been flushed?
I don't *really* care about reflows here because it's only for iOS 7.

**Comment by gaearon** [comment]
FWIW this works well for me:

```js
'use strict';

var viewportUnitsBuggyfill = require('viewport-units-buggyfill'),
    { any } = require('underscore');

viewportUnitsBuggyfill.init();
var patchedViewportStyleNode = document.getElementById('patched-viewport');

function isAppStyleNode(node) {
  return node.tagName === 'STYLE' && node !== patchedViewportStyleNode;
}

function refreshViewportBuggyfill() {
  viewportUnitsBuggyfill.refresh();
  patchedViewportStyleNode.parentNode.appendChild(patchedViewportStyleNode);
}

function handleHeadMutation(mutationRecords) {
  if (any(mutationRecords, record => any(record.addedNodes, isAppStyleNode))) {
    refreshViewportBuggyfill();
  }
}

if (patchedViewportStyleNode) {
  if (typeof MutationObserver !== 'undefined') {
    new MutationObserver(handleHeadMutation).observe(document.head, {
      childList: true
    });
  } else {
    setInterval(refreshViewportBuggyfill, 1500);
  }
}
```

This is probably rather unusual request so closing this.

**Comment by seanemmer** [comment]
Thanks for posting this.  I'm attempting to run Viewport Units Buggyfill as part of a similar Webpack build and am unable to successfully apply the viewport units to my targeted DOM elements.

Had a couple of follow up questions:

1) What is the 'patched viewport' referenced here?  Do I need to re-run this script for each DOM element I am applying CSS viewport properties to (in certain views there are multiple nested elements)?

2) My app is structured as an SPA.  Do I need to wait until the target DOM elements are rendered to execute the script above, or can I execute the script once when the application initializes.

**Comment by gaearon** [comment]
Sorry, I don't remember anything about this 😔
