### ISSUE TITLE
singleton mode problems in IE9

### ISSUE THREAD

**Issue by NekR** [webpack/style-loader#39]
```cssText``` in IE does not supports media queries, i.e. does not return them (I think because of backwards compatibility). So when in single mode (which is by default) you use media queries and that stylesheet with media queries was ```require```d before some other -- then you loose your media queries.

Probably for IE you should store stylesheet in memory (i.e. object/array) and when new modification/addition comes just concatenate all entries and again apply **original** string to stylesheet.

For my case I just disabled singleton mode, but it's not obvious at first glance that you need to do it.

**Comment by sokra** [comment]
@diurnalist

**Comment by diurnalist** [comment]
Ah, interesting - always nice when you can't read out what you write in... Thanks for the report, will look into it.

**Comment by NekR** [comment]
@diurnalist yep, this is IE. Not so much surprise :)

**Comment by zerkms** [comment]
Just experienced the same issue (which mistakenly reported to the webpack repository: https://github.com/webpack/webpack/issues/963) with tiny demo https://github.com/zerkms/webpack-ie9-bug

**Comment by dmvjs** [comment]
Maybe I'm slow, how does one set singleton to false, like this?
```
test: /\.css$/, loader: 'style-loader!css-loader?-singleton' }
```

**Comment by diurnalist** [comment]
@dmvjs you're not slow :) - that's certainly supposed to work. Are you seeing behavior that indicates it's still turned on?

**Comment by diurnalist** [comment]
Sorry about the commit noise, was doing some git wrangling - @NekR @zerkms would you like to try out this fix? I tested it on a project in IE9 without issue.

**Comment by zerkms** [comment]
@diurnalist sure, but I will do tomorrow when in the office

**Comment by dmvjs** [comment]
@diurnalist thanks for confirming how to set the singleton value. i hoped that setting that singleton param would magically fix our IE9 media query issue but it didn't appear to. I'll take a closer look later today.
