### ISSUE TITLE
style/useable not working with bundle loader and ExtractTextPlugin

### ISSUE THREAD

**Issue by jlchereau** [webpack/style-loader#49]
The following config works:

```js
{
    test: /theme\.[a-z]+\.less/,
    loader: "style/useable!css!less"
},
```

but I would like to force all themes in separate bundles.

The following configs do not work:

```js
{
    test: /theme\.[a-z]+\.less/,
    loader: "bundle!style/useable!css!less"
},
```

```js
{
    test: /theme\.[a-z]+\.less/,
    loader: ExtractTextPlugin.extract("style/useable", "css!less")
},
```

use/unuse is perfect for loading/unloading themes. Is there any way to benefit from this feature while forcing themes into separate bundles loaded on demand because it does not make sense to load many themes that a user won't use in the same common bundle?

**Comment by jlchereau** [comment]
Any workaround???

**Comment by sokra** [comment]
This doesn't work. You cannot extract usable styles.

**Comment by jlchereau** [comment]
Thx
