### ISSUE TITLE
Generated image urls *must* be absolute for style!css?sourceMap to work?

### ISSUE THREAD

**Issue by gryzzly** [webpack/style-loader#55]
Is there a way to make images load in browser when using `style-loader/css-loader?sourceMap` without specifying **absolute** url prefix as `publicPath`? 

With this loader:
```js
loaders.push({
  test: /\.scss$/,
  loader: 'style!css?sourceMap')
});
```
This works:
```js
output = {
  path: 'build',
  publicPath: 'http://0.0.0.0:8080/'
  filename: 'bundle.js'
};
```
This doesn't:
```js
output = {
  path: 'build',
  publicPath: '/'
  filename: 'bundle.js'
};
```
In the CSS modules generated as `Blob` the paths are relative to `chrome:blob` or `chrome:devtools` which doesn't refer to the correct assets. 

If my assumption is correct and we always have to set absolute path in `output.publicPath` I will be happy to add a note about this to the docs.

**Comment by sokra** [comment]
> If my assumption is correct and we always have to set absolute path in output.publicPath I will be happy to add a note about this to the docs.

yep. Do you want to add one in a PR?

**Comment by cgaudreau** [comment]
Same problem here. Bit of a confusing bug to run into.

**Comment by dtothefp** [comment]
@gryzzly @clessg if you could offer me any advice I'm running into the same problem. I am compiling SCSS by chaining the `css-loader` with sourcemaps enabled.

I have a demo repo here https://github.com/dtothefp/webpack-font-issue and even though I'm adding the absolute path to the dev server as `publicPath`, I'm still getting the `failed to download` error. Any advice you could offer would be great because I'm at a total loss

**Comment by Darkside73** [comment]
How to deal with HTTPS? Schema-less protocol does not work

**Comment by tizmagik** [comment]
Same question for https

**Comment by Darkside73** [comment]
I've figured out how to solve HTTPS issue. You can use your own dev server (take a look for ```https: true``` option) to serve assets. Here is the example https://gist.github.com/Darkside73/e3b70d72443e0f72b27b

**Comment by tizmagik** [comment]
Ah interesting. Thanks for sharing! I'll try that out. 

For now, I actually ended up going about it slightly differently. Since my main issue was being able to use `url('/images/sample.png')` paths in CSS I defined `?root` query string parameter for the css-loader and then specified `?name=[path][name].[ext]` for the url-loader. This seemed to do the trick without having to specify the full URL in `publicPath`.

**Comment by pixelcure** [comment]
@tizmagik is this how you resolved the disappearing images? was this in webpack.config.js?

**Comment by tizmagik** [comment]
Yes, it seems to work fine even though using `root` is not recommended according to the docs for whatever reason.

**Comment by valerymercury** [comment]
@tizmagik can you provide an example of working config, please?

**Comment by creeperyang** [comment]
@tizmagik It will be helpful if you can provide a sample `webpack.config.js` or just loaders. Thanks in advance.

**Comment by valerymercury** [comment]
@creeperyang `output.publicPath` isn't working for me. As @tizmagik said `root` option helped me to fix bug with background images in css. I resolved my problem with the following config:     
```
var cssRoot = env === 'development' ?
    'root=' + path.join(__dirname, 'app/assets') + '&' : ''

loaders: [
    {
        test: /\.scss$/,
        include: path.resolve(__dirname, 'app/styles'),
        loader: ExtractTextPlugin.extract('style', 'css?'+ cssRoot +
            'sourceMap!postcss!sass?sourceComments&' +
            'includePaths[]=' + (path.resolve(__dirname, './bower_components/compass-mixins/lib/'))
        )
    }
]
```

**Comment by tizmagik** [comment]
@creeperyang sorry for the late reply, just saw this.

@valerymercury yeap, that's basically what I have as well. Here's mine if it's any more helpful:

```js
const rootPublic = path.resolve('./public');
const LOCAL_IDENT_NAME = 'localIdentName=[name]_[local]_[hash:base64:5]';
const CSS_LOADER = `css?sourceMap&${LOCAL_IDENT_NAME}&root=${rootPublic}` + (DEBUG ? '&minimize' : '');

// ... loaders:

loaders: [
  {
    test: /\.css$/,
    loader: DEBUG ? `style!${CSS_LOADER}` : ExtractTextPlugin.extract('style', CSS_LOADER)
  }, // ...
]
```

**Comment by davidhouweling** [comment]
Has this been tested with relative pathed images (e.g. `url(image.png)`? It seems the solution provided is for absolute path images (e.g. `url(/image.png)`. I can't seem to use either solution suggested.

**Comment by tizmagik** [comment]
So unfortunately, this does not work when using CSS Modules, `:local`.

Has anyone been able to find another solution?

**Comment by schickling** [comment]
Facing the same problem at the moment...

**Comment by unimonkiez** [comment]
Me too

**Comment by Strate** [comment]
#96

**Comment by mbritton** [comment]
+1

**Comment by simshanith** [comment]
Still not working for me with an absolute public path, e.g. `/build/`. Even including the full public URL e.g. `http://example.com/build/` does not seem to work.

**Comment by Pines-Cheng** [comment]
meet the same question, just working for me with an absolute public path.

**Comment by muralim4242** [comment]
`url(${require('app/images/Rectangle-9.jpg')})`

**Comment by olieidel** [comment]
just stumbled over this. if setting `publicPath` is not working for you, you probably are making the same mistake as I was by setting `publicPath` in the `devServer`config. it should be set in the webpack root config object in `output`.  have a look:

doesn't work:
```javascript
// your webpack config
{
  devServer: {
    publicPath: 'http://127.0.0.1:8888/'
   // ... more devServer config
  }
// ... more webpack config
}
```

works for me:
```javascript
{
  output: {
    publicPath: 'http://127.0.0.1:8888/'
    // ... more webpack output config
  }
  devServer: {
   // ... your devServer config
  }
// ... more webpack config
}
```

be sure to only set it in dev, who knows what this would do in your production build. good luck!

**Comment by lysenkobv** [comment]
@simshanith to make it work specify `publicPath` for `file-loader`
```javascript
{
    test: /\.(png|jpg|gif|svg|eot|ttf|woff|woff2|json|xml|ico)$/,
    loader: 'file-loader',
    query: {
        outputPath: 'assets/',
        publicPath: 'http://localhost:8080/', <- here
        emitFile: true
    }
}
```

it will change URL in your CSS from relative to absolute

**Comment by urikphytech** [comment]
Hi! I've tried every combination I could possibly think of and I can't understand why my images aren't found... 
Here is my configuration: 
```
output: {
    path: distPath,
    // Set proper base URL for serving resources
    publicPath: '/',
    // The output filename of the entry chunk, relative to `path`
    // [name] - Will be set per each key name in `entry`
    filename: 'bundle.[hash].js'
  },

.....

// SCSS
      {
        test: /\.(css|scss)$/,
        loaders: [
          'style-loader',
          'css-loader?root=' + encodeURIComponent(appPath),
          'postcss-loader',
          'sass-loader?includePaths[]=' + encodeURIComponent(appPath)
        ]
      },

{
        test: /\.(jpe?g|png|gif|svg)(\?.*)?$/i,
        loader: 'file-loader',
        options: {
          name: '[path][name].[hash].[ext]',
          publicPath: 'http://localhost:8080/', --> Added this because suggested here (in webpack 1 it worked without this
        },
      }
```


And i'm requiring the images via scss:
`
background-image: url('/assets/images/login/background_4.jpg');
`
Webpack output is:
<img width="1234" alt="screen shot 2017-06-03 at 7 58 07" src="https://cloud.githubusercontent.com/assets/25924697/26750779/f31da5a4-4832-11e7-8c84-9be9c86859c8.png">

Which is strange, because it used to be: '/assets/images/.....' without the '/Users/uriklar/' part

Any idea what i'm missing here??
Thanks!
Uri

**Comment by uriklar** [comment]
Ok, so my issue wasn't relate (I'll delete my comment if maintainers prefer), but in case someone does get here with the same problem as me, what fixes it for me was adding the: context option to file-loader (i'm actually using url-loader) with the base url that assets need to be loaded from.

**Comment by xgqfrms-gildata** [comment]
# `output.publicPath` & `output.path`

https://github.com/gildata/RAIO/issues/276#issuecomment-354964693

**Comment by robbie-hinman** [comment]
It seems with css sourceMaps enabled, even with publicPath set, styles (including bg images) are not applied.  But what is odd is that I can see them in the inspector.  If I turn the style off and on again _then_ the style is applied.

The below shows the page on initial load, showing a body background of paleturquoise in the dev console but the displayed background is white.  
![image](https://user-images.githubusercontent.com/14951190/35007920-cbf21fe8-faaf-11e7-82c3-4a667998405c.png)
Unchecking and checking a style will then show the correct styles.  If the dev console is not open you still have the issue.

repo [here](https://github.com/robbie-hinman/webpack3-basic/tree/css-sourcemaps-breaking-styles)
