### ISSUE TITLE
Allow to specify the position to insert new link/style tag

### ISSUE THREAD

**Issue by pkorzh** [webpack/style-loader#56]
i want to be able to specify where to insert new link/style nodes. in my project bower deps. css should go before custom css, witch is built in one bundle and included in head tag.

having query option like `insertAt: 'top' / 'bottom` would do the trick

**Comment by sokra** [comment]
Feel free to send a PR that adds such a query parameter.

**Comment by Anahkiasen** [comment]
:+1: for this

**Comment by vvo** [comment]
This is already done, can be closed

**Comment by SpaceK33z** [comment]
Jup, this was fixed in #69 months ago.
