### ISSUE TITLE
style-loader generates `if (false)` code

### ISSUE THREAD

**Issue by sjoerdvisscher** [webpack/style-loader#62]
I get a lot of warnings if I combine `style-loader` and the uglify plugin. The generated `if (false)` results in "Condition always false" and "Dropping unreachable code" warnings from uglify. Why not just skip that part entirely when emitting the code?

**Comment by sokra** [comment]
it generates `if(module.hot)` which is processed by webpack.

**Comment by sjoerdvisscher** [comment]
Ah, cool stuff. Then uglify should not emit warnings I guess.
