### ISSUE TITLE
Brief paragraph describing what the style-loader does?

### ISSUE THREAD

**Issue by michaeljones** [webpack/style-loader#70]
### Steps to reproduce:
1. Forget everything you know about webpack
2. See style loader be used in a webpack config file
3. Desire to know what it does
4. Google style-loader and go to github project
### Expected Result

Find some brief documentation describing what the style loader does and its role in the webpack pipeline.
### Actual Result

Find description of usage but no reference to what it does.
### Notes

I'm new to webpack and trying to understand how best to manage my CSS/SASS code. At the moment I'm requiring it into my JS code and using the style-loader and then extracting it out with the ExtractTextPlugin. I'm looking for other approaches and so want to better understand what is currently going on and so would love to understand the exact role that the style-loader plays.

Cheers,
Michael

**Comment by oliverbenns** [comment]
+1, right there with you.

**Comment by arturmuller** [comment]
+1, same here.

**Comment by Zorgatone** [comment]
:+1:

**Comment by tizmagik** [comment]
+1, I'm with you, the documentation on style-loader (and webpack in general) could use some love, I think.

But, looking at the code, this is basically what it does:
https://github.com/webpack/style-loader/blob/master/index.js#L12

>  Adds some css to the DOM by adding a <style> tag",

It works in conjunction with the css-loader to put the appropriate CSS there. The reason why ExtractTextPlugin is helpful is that in production mode, to avoid FOUC, you'd want to extract your CSS into a separate stylesheet and load that at the top of your page.

**Comment by Zorgatone** [comment]
yeah, I'd really like to know how to bundle CSS files to a single external CSS file, without embedding everything with the style tag

**Comment by tizmagik** [comment]
@Zorgatone that's what the [ExtractTextPlugin](https://github.com/webpack/extract-text-webpack-plugin) is for! :)

**Comment by SpaceK33z** [comment]
This was fixed by #120.
