### ISSUE TITLE
webpack-dev-server not watching changes in my imports

### ISSUE THREAD

**Issue by newtonianb** [webpack/style-loader#71]
I just setup webpack-dev-server below are some of my configs

**assets/entry.js**

```
require('./styles/style')
```

**assets/styles/style.scss**

```
@imports ('utilities/other_style.scss')
```
-  Changes to style.scss get detected and rebuilds
-  Changes to imported file other_style do not get detected

Is this supposed to work? What's the solution for this with webpack-dev-server and hot module replacement setup?

As a work around what I could do is have all my imports be required from my entry.js file (that works) the issue is what about my global SCSS variables and mixins, I would have to import them in each file, wouldn't that slow things down alot? What is the right way to go about this?

**Comment by KeitIG** [comment]
any news on this ? I'm getting the same problem.

**Comment by SpaceK33z** [comment]
As long as you use [sass-loader](https://github.com/jtangelder/sass-loader), this works now.
