### ISSUE TITLE
styles.use need callback

### ISSUE THREAD

**Issue by jeongsd** [webpack/style-loader#74]
hi i'm using webpack style-loader with React.js
i trying to load css with styles.use() like this

```javascript
componentWillMount() {
      styles.use();
    }
```

But CSS file is injected after react's render() method.

how can I know inject state? or using with callback?

**Comment by rayshan** [comment]
@jeongsd did you ever find a solution to this? Also running into issues with styles injected after initial render when not using useable API.

**Comment by essmahr** [comment]
+1

**Comment by holgersindbaek** [comment]
+1
