### ISSUE TITLE
How to tell style-loader to include node_modules folder for sass import?

### ISSUE THREAD

**Issue by f15gdsy** [webpack/style-loader#85]
I want to import a scss file I installed through npm in my scss code.
Can I tell style loader to include node_modules for sass import?

Thanks!

**Comment by Cleod9** [comment]
i'm surprised no one answered this, but have you tried the following when using with `sass-loader`?

```scss
import "~packagename/lib/styles.scss";
```
`sass-loader` allows the "~" to resolve to the module directories defined by webpack (`node_modules`, `web_modules`, etc). Just make sure you get your loaders in the correct order though when you import this sass file:
```js
require("style!raw!sass!./file.scss");
```

**Comment by SpaceK33z** [comment]
Closing since question has been answered.
