### ISSUE TITLE
Request: allow style to be created but not injected

### ISSUE THREAD

**Issue by ronkorving** [webpack/style-loader#87]
With a query parameter, we could use the `<style>` object, but insert it into the document at our own convenience. It would be useful to me. Not sure how others look at this idea?

**Comment by ronkorving** [comment]
If I make a PR for this, is there any chance of it getting merged?

**Comment by ronkorving** [comment]
@sokra I've been trying to figure out how to implement this, but it looks next to impossible with the way this loader is set up. Perhaps I'm wrong, but then I would love some pointers in the right direction. If I really want this, am I better off making my own loader?

**Comment by tzapu** [comment]
i m not sure what features you are loosing, but i was able to do the above using css-to-string-loader loader and just adding the style var manually

**Comment by ronkorving** [comment]
How do you achieve that? In the mean time I released https://www.npmjs.com/package/dom-loader that can be used for this (and other elements).

**Comment by tzapu** [comment]
i use a react render to iframe component and i needed css reset to be rendered in the iframe, not in the main head. using css to string, i load the css in a var and pass it to the Frame component
```
import mainStyles from 'normalize.css';
...
  <Frame style={styles.frame} scrolling={'no'}
             initialContent={`<!DOCTYPE html><html style="width: 100%; height: 100%;">
             <head><style type="text/css">${mainStyles}</style></head>
             <body>
             <div></div>
             </body></html>`}>
```

**Comment by ronkorving** [comment]
What is "CSS to string"?

**Comment by tzapu** [comment]
https://www.npmjs.com/package/css-to-string-loader

**Comment by ronkorving** [comment]
Got it, I didn't know you meant it that literally :)
So what I do with my dom-loader is `{ test: /\.css$/, loader: 'dom?tag=style&attrs[]=type:text/css!css' }`

**Comment by SpaceK33z** [comment]
@ronkorving, was your issue fixed with that loader? I don't think this functionality should be in style-loader.

**Comment by ronkorving** [comment]
I went with my alternative at the time, so can't really say. It probably worked fine. I'll close this issue, sorry for having kept it open so long.
